#!/bin/bash 

EditMenu () {
( gio open "$(grep -e "menuFile" ~/.blackboxrc|awk '{print $2}'|sed 's/ //g')" ) || ( xdg-open "$(grep -e "menuFile" ~/.blackboxrc|awk '{print $2}'|sed 's/ //g')")
}

Help () {
   echo "Show Blackbox WM menus from command-line."
   echo 
   echo "Syntax: bbmenu [-1|2|3|4|e|h]"
   echo "options:"
   echo "1     Show Icon Menu."
   echo "2     Show Workspace Menu."
   echo "3     Show Root Main Menu."
   echo "4     Show Control Menu (X Window Context...)."
   echo "e     Edit menuFile."
   echo "h     Print this help message and exit."
   echo
}

while getopts ":1234eh" option; do
   case $option in
    1)	xdotool click --window 1923 1
        exit;;
    2)	xdotool click --window 1923 2
        exit;;
    3)	xdotool click --window 1923 3
        exit;;
    4)	xdotool keydown Super ; xdotool click 3 ; sleep 0.2 && xdotool keyup Super
        exit;; 
    e)   EditMenu
        exit;;
    h)   Help
        exit;;
   esac
done
