#!/bin/bash 
# jxpx@2024

while getopts ":01234" option; do
   case $option in
    0)  xwininfo -root|grep "Window id:"|awk '{print $4}'
        exit;;
    1)	xdotool click --window "$(bbmenu -0)" 1
        exit;;
    2)	xdotool click --window "$(bbmenu -0)" 2
        exit;;
    3)	xdotool click --window "$(bbmenu -0)" 3
        exit;;
    4)	xdotool keydown Super ; xdotool click 3 ; sleep 0.2 && xdotool keyup Super
        exit;;
   esac
done
